# Generated by Django 4.2.5 on 2023-09-07 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='Word')),
                ('meaning', models.TextField(verbose_name='Meaning')),
                ('transliteration', models.CharField(max_length=100, verbose_name='Transliteration')),
                ('example', models.TextField(verbose_name='Example')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Words',
            },
        ),
    ]
